version: "3.2"

services:
  database:
    image: postgres:13.1-alpine
    container_name: database
    hostname: database
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - pretix

  redis:
    image: redis:latest
    container_name: cache
    networks:
      - pretix

  pretix:
    image: pretix/standalone:stable
    container_name: pretix
    depends_on:
      - database
      - redis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/pretix.cfg:/etc/pretix/pretix.cfg
    networks:
      - pretix

networks:
  pretix:
